[telegram]
token = ""
admins = [
    23646077, # riccardo
    1159605359 # flytek mod
]
errors_log = 0
chat_invite_link = ""

[database]
engine_string = "sqlite:///bot.db"

[settings]
sent_to_staff_message = true
broadcast_message_edits = true

[handlers]
manifest = "manifest_feedback"

[webcal]
api_key = ""
legal_subcal_name = ""
free_subcal_name = ""
other_subcal_name = ""
