[telegram]
token = ""
admins = [
    23646077, # riccardo
    1159605359 # flytek mod
]

[database]
engine_string = "sqlite:///bot.db"

[settings]
sent_to_staff_message = true
broadcast_message_edits = true

[handlers]
import = [
    ""
]
