[telegram]
token = "" # your bot's token (get it from @BotFather)
admins = [] # list of super admins, place your Telegram ID here

[settings]
broadcast_message_edits = true # whether to broadcast message edits from the staff to the user chat
backup_events = true # download flyers, for archival purposes
tell_ban_reason = false # tell the user why they were banned, if a reason was provided (doesn't apply to shadowbans)
save_chat_member_from_message = false # when a message in a group is received, check whether we saved the user membership in that group
protected_admin_replies = true # whether admin replies sent to the user can be forwarded/copied
invite_link_join_request = false # wether bot-generated invite links should create a join request
notify_events_validity = true # notify the staff when an invalid event is posted, or when an invalid event becomes valid
radar_enabled = [] # always enable /radar23 for these user ids
parties_message_weekday = 0 # weekday when to post new messages, 0 = Monday
parties_message_hour = 9 # hour when to post new messages, 24h format
parties_message_job_frequency = 60 # in minutes
parties_message_pin = true # pin parties messages when they are sent (the service message will be deleted)

[handlers]
# which handlers manifest to use, depending on what the bot should do
manifest = "manifest"
# which modules to import from the manifest, will load modules in the `[mode]` or `[+]` sections
mode = "bbr"
