[telegram]
token = "" # your bot's token (get it from @BotFather)
admins = [] # list of super admins, place your Telegram ID here

[settings]
set_commands = true # whether to set commands or not
db_save_json = true # whether to save or not a message's json, when needed (doesn't apply to Event and PartiesMessage)
broadcast_message_edits = true # whether to broadcast message edits from the staff to the user chat
backup_events = true # download flyers, for archival purposes
allow_events_from_any_chat = false # if false, the bot will only consider events coming from the current events chat
tell_ban_reason = false # tell the user why they were banned, if a reason was provided (doesn't apply to shadowbans)
save_chat_member_from_message = false # when a message in a group is received, check whether we saved the user membership in that group
protected_admin_replies = false # (staff) whether admin replies sent to the user can be forwarded/copied
protected_admin_replies_evaluation = true # (evaluation chat) whether admin replies sent to the user can be forwarded/copied
invite_link_join_request = false # wether bot-generated invite links should create a join request
notify_events_validity = true # notify the staff when an invalid event is posted, or when an invalid event becomes valid
radar_password = "" # if not empty, only users who sent this regex will be able to use /radar, rgardles of their users chat's membership
parties_message_job_frequency = 55 # in minutes, how often to run the job that will post the parties list in the events chat
events_chat_deeplink_cooldown = 10800 # in minutes, 10800 = 3 hours. 0 to disable
unpin_reqests_messages = false # wehn a request is received and forwarded to the evaluation chat, unpin the evaluation chat fowarded post

[handlers]
# which handlers manifest to use, depending on what the bot should do
manifest = "manifest"
# which modules to import from the manifest, will load modules in the `[mode]` or `[+]` sections
mode = "bbr"
