[telegram]
token = "" # your bot's token from @BotFather
# list of super admins, place your Telegram ID here
admins = [
    23646077, # riccardo
    1159605359 # flytek mod
]

[settings]
# these are the default values, no need to change them. they can be changed on the fly from the bot
broadcast_message_edits = true
backup_events = true
tell_ban_reason = false
radar_enabled = []

[handlers]
# which handlers manifest to use, depending on what the bot should do
manifest = "manifest"
# which modules to import from the manifest, will load modules in the `[mode]` or `[+]` section
mode = "bbr"
