[telegram]
token = "" # your bot's token from @BotFather
# list of super admins, place your Telegram ID here
admins = [
    23646077, # riccardo
    1159605359 # flytek mod
]

[settings]
broadcast_message_edits = true # whether to broadcast message edits from the staff to the user chat
backup_events = true # download flyers, for archival purposes
tell_ban_reason = false # tell the user why they were banned, if a reason was provided (doesn't apply to shadowbans)
save_chat_member_from_message = false # when a message in a group is received, check whether we saved the user membership in that group
protected_admin_replies = true # whether admin replies sent to the user can be forwarded/copied
radar_enabled = [] # always enable /radar23 for these user ids

[handlers]
# which handlers manifest to use, depending on what the bot should do
manifest = "manifest"
# which modules to import from the manifest, will load modules in the `[mode]` or `[+]` section
mode = "bbr"

[log]
events_chat_member_updates = true
users_chat_member_updates = true
