class Emoji:
    BANNED = "🚫"
    SLEEPING = "😪"
    WARNING = "⚠️"
    LENS = "🔎"
    ENVELOPE = "✉️"
    PENCIL = "✏️"
    TRASH = "🚮"
    EARTH = "🌍"
    LINK = "🔗"
    PEOPLE = "👥"
    HELLO = "👋"
    SIGN = "✍️"
    HANDSHAKE = "🤝"
    PEACE = "🖖"
    BELL = "🛎"
    CAMERA = "📷"
    ALIEN = "👽"
    CANCEL = "❌"
    DONE = "✅"
    FORWARD = "⏩"
    RABBIT = "🐰"
    QUESTION = "❓"
    PIRATE = "🏴‍☠️"
    DISCO = "🪩"
    PIN_2 = "📌"


class Flag:
    ITALY = "🇮🇹"
    FRANCE = "🇫🇷"
