class Emoji:
    BANNED = "🚫"
    SLEEPING = "😪"
    WARNING = "⚠️"
    LENS = "🔎"
    ENVELOPE = "✉️"
    PENCIL = "✏️"
    TRASH = "🚮"
    EARTH = "🌍"
    LINK = "🔗"
    PEOPLE = "👥"
    HELLO = "👋"
    SIGN = "✍️"
    HANDSHAKE = "🤝"
    PEACE = "🖖"
    BELL = "🛎"
    CAMERA = "📷"
    ALIEN = "👽"
    CANCEL = "❌"
    DONE = "✅"
    FORWARD = "⏩"
    RABBIT = "🐰"
    QUESTION = "❓"
    PIRATE = "🏴‍☠️"
    DISCO = "🪩"
    PIN_2 = "📌"
    ANNOUNCEMENT = "📣"
    TRUCK = "🚛"


class Flag:
    ALBANY = "🇦🇱"
    ARGENTINA = "🇦🇷"
    AROUND_THE_WORLD = "🌍"
    AUSTRIA = "🇦🇹"
    BELGIUM = "🇧🇪"
    BULGARIA = "🇧🇬"
    CHILE = "🇨🇱"
    COLOMBIA = "🇨🇴"
    CROATIA = "🇭🇷"
    CZECH_REPUBLIC = "🇨🇿"
    DENMARK = "🇩🇰"
    ENGLAND = "🇬🇧"
    EUROPE = "🇪🇺"
    FINLAND = "🇫🇮"
    FRANCE = "🇫🇷"
    GERMANY = "🇩🇪"
    GREECE = "🇬🇷"
    HUNGARY = "🇭🇺"
    IRELAND = "🇮🇪"
    ITALY = "🇮🇹"
    MOROCCO = "🇲🇦"
    NETHERLANDS = "🇳🇱"
    NORWAY = "🇳🇴"
    POLAND = "🇵🇱"
    PORTUGAL = "🇵🇹"
    ROMANIA = "🇷🇴"
    SCOTLAND = "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
    SLOVAKIA = "🇸🇰"
    SLOVENIA = "🇸🇮"
    SPAIN = "🇪🇸"
    SWISS = "🇨🇭"
    SWEDEN = "🇸🇪"


