class Emoji:
    BANNED = "🚫"
    SLEEPING = "😪"
    WARNING = "⚠️"
    LENS = "🔎"
    ENVELOPE = "✉️"
    PENCIL = "✏️"
    TRASH = "🚮"
    EARTH = "🌍"
    LINK = "🔗"
    PEOPLE = "👥"
    HELLO = "👋"
    SIGN = "✍️"
    HANDSHAKE = "🤝"
    PEACE = "🖖"
